% ============================================================
% File: src/common/spectra/export_ch6_table_tex.m
% ============================================================
function export_ch6_table_tex(outs, tex_path, opts)
%EXPORT_CH6_TABLE_TEX Export the Chapter 6 summary table to LaTeX.
% Thesis link: Chapter 6.4 (cross-case summary of spectra and PCG results).
% The routine writes a compact table with the main indicators for FETI-DP
% and BDDC in the presentation order used in the thesis.
%
% Inputs:
%   outs     : either a cell array {out1,out2,...} or a struct array [out1,out2,...]
%              where each "out" is produced by ch6_run_case.m.
%   tex_path : output .tex file path (e.g. output/tables/ch6/table_ch6_summary.tex)
%   opts     : optional struct with fields:
%              - include_table_env : true/false (default true)
%              - caption           : string (default '')
%              - label             : string (default '')
%              - booktabs          : true/false (default true)
%              - num_fmt           : numeric format for eigenvalues (default '%.3e')
%              - relres_fmt        : numeric format for relres (default '%.3e')
%              - kappa_fmt         : numeric format for kappa (default '%.3e')
%              - fontsize_cmd      : LaTeX font size command (default '\small')
%
% Output:
%   Writes tex_path. Intended for inclusion in thesis via \input{...}.

  % ----------------------------
  % Input validation + defaults
  % ----------------------------
  if nargin < 2 || nargin > 3
    error('export_ch6_table_tex:InvalidNargin', ...
          'Expected inputs (outs, tex_path [, opts]).');
  end

  if nargin < 3 || isempty(opts)
    opts = struct();
  end
  if ~isstruct(opts)
    error('export_ch6_table_tex:InvalidOpts', 'opts must be a struct (or []).');
  end

  if ~ischar(tex_path) && ~isstring(tex_path)
    error('export_ch6_table_tex:InvalidPath', 'tex_path must be a string.');
  end
  tex_path = char(tex_path);

  if ~isfield(opts, 'include_table_env') || isempty(opts.include_table_env)
    opts.include_table_env = true;
  end
  if ~islogical(opts.include_table_env) || ~isscalar(opts.include_table_env)
    error('export_ch6_table_tex:InvalidIncludeEnv', ...
          'opts.include_table_env must be a logical scalar.');
  end

  if ~isfield(opts, 'caption') || isempty(opts.caption)
    opts.caption = '';
  end
  if ~isfield(opts, 'label') || isempty(opts.label)
    opts.label = '';
  end

  if ~isfield(opts, 'booktabs') || isempty(opts.booktabs)
    opts.booktabs = true;
  end
  if ~islogical(opts.booktabs) || ~isscalar(opts.booktabs)
    error('export_ch6_table_tex:InvalidBooktabs', ...
          'opts.booktabs must be a logical scalar.');
  end

  if ~isfield(opts, 'num_fmt') || isempty(opts.num_fmt)
    opts.num_fmt = '%.3e';
  end
  if ~isfield(opts, 'relres_fmt') || isempty(opts.relres_fmt)
    opts.relres_fmt = '%.3e';
  end
  if ~isfield(opts, 'kappa_fmt') || isempty(opts.kappa_fmt)
    opts.kappa_fmt = '%.3e';
  end

  if ~isfield(opts, 'fontsize_cmd') || isempty(opts.fontsize_cmd)
    opts.fontsize_cmd = '\small';
  end

  % Normalize outs to a cell array for uniform processing
  if iscell(outs)
    outs_cell = outs;
  elseif isstruct(outs)
    outs_cell = num2cell(outs);
  else
    error('export_ch6_table_tex:InvalidOuts', ...
          'outs must be a cell array or struct array.');
  end

  if isempty(outs_cell)
    error('export_ch6_table_tex:EmptyOuts', 'outs is empty.');
  end

  % Ensure output directory exists
  outdir = fileparts(tex_path);
  if ~isempty(outdir) && ~exist(outdir, 'dir')
    mkdir(outdir);
  end

  % ----------------------------
  % Open file
  % ----------------------------
  fid = fopen(tex_path, 'w');
  if fid < 0
    error('export_ch6_table_tex:OpenFailed', ...
          'Could not open file for writing: %s', tex_path);
  end
  cleaner = onCleanup(@() fclose(fid)); %#ok<NASGU>

  % ----------------------------
  % Table header
  % ----------------------------
  if opts.include_table_env
    fprintf(fid, '%% Auto-generated by export_ch6_table_tex.m\n');
    fprintf(fid, '\\begin{table}[t]\n');
    fprintf(fid, '  \\centering\n');
    fprintf(fid, '  %s\n', opts.fontsize_cmd);
  else
    fprintf(fid, '%% Auto-generated by export_ch6_table_tex.m (tabular only)\n');
    fprintf(fid, '%s\n', opts.fontsize_cmd);
  end

  % 2 case columns + 6 (FETI-DP) + 6 (BDDC) = 14 columns
  fprintf(fid, '  \\begin{tabular}{r c | r r r r r r | r r r r r r}\n');

  if opts.booktabs
    fprintf(fid, '    \\toprule\n');
  else
    fprintf(fid, '    \\hline\n');
  end

  fprintf(fid, '    \\multicolumn{2}{c|}{} & ');
  fprintf(fid, '\\multicolumn{6}{c|}{FETI-DP} & ');
  fprintf(fid, '\\multicolumn{6}{c}{BDDC} \\\\\n');

  fprintf(fid, '    \\multicolumn{2}{c|}{Case} & ');
  fprintf(fid, '$n_{\\lambda}$ & $\\lambda_{\\min}$ & $\\lambda_{\\max}$ & $\\kappa$ & it & relres & ');
  fprintf(fid, '$n_{\\hat{u}}$ & $\\lambda_{\\min}$ & $\\lambda_{\\max}$ & $\\kappa$ & it & relres \\\\\n');

  if opts.booktabs
    fprintf(fid, '    \\midrule\n');
  else
    fprintf(fid, '    \\hline\n');
  end

  % ----------------------------
  % Rows
  % ----------------------------
  for k = 1:numel(outs_cell)
    out = outs_cell{k};

    % Case info
    N  = getfield_default_(out, {'cfg','n'}, NaN);
    sx = getfield_default_(out, {'cfg','nSubX'}, NaN);
    sy = getfield_default_(out, {'cfg','nSubY'}, NaN);

    case_mesh = int_or_dash_(N);
    case_sub  = sprintf('%sx%s', int_or_dash_(sx), int_or_dash_(sy));

    % FETI-DP stats/spec
    nLam   = getfield_default_(out, {'fetidp','n'}, NaN);
    itF    = getfield_default_(out, {'fetidp','stats','iter'}, NaN);
    rrF    = getfield_default_(out, {'fetidp','stats','relres'}, NaN);
    skipF  = getfield_default_(out, {'fetidp','spec_skipped'}, true);

    if ~skipF
      lminF = getfield_default_(out, {'fetidp','spec','lmin'}, NaN);
      lmaxF = getfield_default_(out, {'fetidp','spec','lmax'}, NaN);
      kapF  = getfield_default_(out, {'fetidp','spec','kappa'}, NaN);
      f_lmin = num_or_dash_(lminF, opts.num_fmt);
      f_lmax = num_or_dash_(lmaxF, opts.num_fmt);
      f_kap  = num_or_dash_(kapF,  opts.kappa_fmt);
    else
      f_lmin = '--';
      f_lmax = '--';
      f_kap  = '--';
    end

    f_n  = int_or_dash_(nLam);
    f_it = int_or_dash_(itF);
    f_rr = num_or_dash_(rrF, opts.relres_fmt);

    % BDDC stats/spec
    nHat  = getfield_default_(out, {'bddc','n'}, NaN);
    itB   = getfield_default_(out, {'bddc','stats','iter'}, NaN);
    rrB   = getfield_default_(out, {'bddc','stats','relres'}, NaN);
    skipB = getfield_default_(out, {'bddc','spec_skipped'}, true);

    if ~skipB
      lminB = getfield_default_(out, {'bddc','spec','lmin'}, NaN);
      lmaxB = getfield_default_(out, {'bddc','spec','lmax'}, NaN);
      kapB  = getfield_default_(out, {'bddc','spec','kappa'}, NaN);
      b_lmin = num_or_dash_(lminB, opts.num_fmt);
      b_lmax = num_or_dash_(lmaxB, opts.num_fmt);
      b_kap  = num_or_dash_(kapB,  opts.kappa_fmt);
    else
      b_lmin = '--';
      b_lmax = '--';
      b_kap  = '--';
    end

    b_n  = int_or_dash_(nHat);
    b_it = int_or_dash_(itB);
    b_rr = num_or_dash_(rrB, opts.relres_fmt);

    % Print row (14 columns, all as strings -> no ASCII-code issues)
    fprintf(fid, ...
      '    %s & %s & %s & %s & %s & %s & %s & %s & %s & %s & %s & %s & %s & %s \\\\\n', ...
      case_mesh, case_sub, ...
      f_n, f_lmin, f_lmax, f_kap, f_it, f_rr, ...
      b_n, b_lmin, b_lmax, b_kap, b_it, b_rr);
  end

  % ----------------------------
  % Footer
  % ----------------------------
  if opts.booktabs
    fprintf(fid, '    \\bottomrule\n');
  else
    fprintf(fid, '    \\hline\n');
  end

  fprintf(fid, '  \\end{tabular}\n');

  if opts.include_table_env
    if ~isempty(opts.caption)
      fprintf(fid, '  \\caption{%s}\n', opts.caption);
    end
    if ~isempty(opts.label)
      fprintf(fid, '  \\label{%s}\n', opts.label);
    end
    fprintf(fid, '\\end{table}\n');
  end
end


% ============================================================
% Local helpers
% ============================================================

function v = getfield_default_(s, path_cells, default_val)
%GETFIELD_DEFAULT_  Safe nested getter.
% Example: {'fetidp','stats','iter'}

  v = default_val;

  if ~isstruct(s)
    return;
  end

  cur = s;
  for i = 1:numel(path_cells)
    key = path_cells{i};
    if ~isstruct(cur) || ~isfield(cur, key)
      return;
    end
    cur = cur.(key);
  end

  v = cur;
end

function s = int_or_dash_(x)
%INT_OR_DASH_  Format integer or return '--' for missing/NaN.
  if isempty(x) || ~isfinite(x)
    s = '--';
    return;
  end
  s = sprintf('%d', round(x));
end

function s = num_or_dash_(x, fmt)
%NUM_OR_DASH_  Format number with fmt or return '--' for missing/NaN.
  if isempty(x) || ~isfinite(x)
    s = '--';
    return;
  end
  s = sprintf(fmt, x);
end